services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - IDP_DOMAIN=${IDP_DOMAIN}
      - ISSUER=${ISSUER}
      - AUDIENCE=${AUDIENCE}
      - ALGORITHM=${ALGORITHM}
      - ALLOW_ORIGINS=["http://frontend:3000"]
      - RATE_LIMIT=${RATE_LIMIT}
      - RATE_LIMIT_PERIOD=${RATE_LIMIT_PERIOD}
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL="http://backend:3000"
    depends_on:
      - backend

